version: "3.9"

services:
  api_service:
    build:
      context: api_service
      dockerfile: dockerfile.dev
    ports:
      - "9000:9000"
    container_name: et_api_service
    volumes:
      - ./api_service:/service
    # depends_on:
    #   - mysql

  mysql:
    image: mysql:8.0.27
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rl01111998
      MYSQL_DATABASE: database

volumes:
  db-data:
